// AI Kamai Prompt Vault — expansion pack v1.1 (categories: Video, Data, Ecommerce, Writing, Team, Money Basics, Learning, Tools)
var EXTRA_PROMPTS = [
// ============ VIDEO & YOUTUBE ============
{c:"Video", t:"YouTube title jo click ho", p:"Meri video ka topic: [topic]. Audience: [audience]. Mujhe 10 YouTube titles do — click karne ke liye irresistible, par clickbait jhootha nahi. Mix: curiosity ('ye nahi pata tha'), number wale ('7 cheezein'), contrarian, 'mistake' wale, aur 'how to' wale. Har title 60 chars max. Saath me 3-line video description bhi — pehli line hook, keywords natural, CTA end me."},
{c:"Video", t:"Thumbnail concept text wala", p:"Mere YouTube video ke liye thumbnail concept banao. Video topic: [topic]. Mujhe: (1) 5 text options (3-5 words max, bada font style), (2) har text ke saath background visual idea (screenshot? face? arrow? number?), (3) ek 'anti-design' rule — kitna text NAHI hona chahiye, (4) A/B test plan: pehle 48 ghante me kaunsa title+thumb combination try karu. Thumbnail me jhootha shock nahi — honest curiosity."},
{c:"Video", t:"Long video ka full script", p:"Mujhe [topic] pe ek 10-minute YouTube video ka script chahiye. Audience [audience] — beginner. Structure: 0-30s hook (kya milega dekho, na ki 'namaskar doston'), 30s-2min context + problem, 2-9min main content (3-4 sections, har section me example + screen note), 9-10min recap + CTA. Hinglish, conversational, jaise dost ko samjha rahe ho. Har 2 minute pe ek 'pattern interrupt' line — taaki retention na gire. B-roll/text overlay notes bracket me daal do."},
{c:"Video", t:"Ek video se shorts nikaalna", p:"Ye meri video ka transcript hai: [paste]. Isse 5 shorts nikaalo — har ek 45 sec max, apna hook (pehle 2 sec me), ek hi point, aur CTA full video ki taraf. Shorts aise cut ho ki standalone samajh aaye. Har short ke liye: caption + 3 hashtags + pinned comment idea."},
{c:"Video", t:"B-roll shot list ghar se", p:"Mere video topic: [topic]. Mujhe 10 b-roll shots ki list do jo main ghar/desk se phone pe shoot kar saku — koi setup nahi. Har shot: kya hai, kaise shoot karu (angle, light), kitne second ka. Editing me kahan use hoga ye bhi likho — intro ke liye / point ke beech / boriyat todne ke liye."},
{c:"Video", t:"Podcast/interview ke sawal", p:"Main [guest type] ka interview lene wala hoon. Mujhe 15 sawal do — flow me: 3 warmup (easy, confidence), 6 deep (unki journey, galtiyan, decisions), 3 spicy (contrarian opinions, 'ye batao jo log nahi puchte'), 3 wrap-up (advice, future, plug unka kaam). Har sawal ke saath 1 follow-up line. Hindi/English mix — main Hinglish me puchunga."},
{c:"Video", t:"Video SEO — description + tags", p:"Meri video: [topic + rough description]. Mujhe: (1) SEO title (under 60 chars, keyword aage), (2) description — pehli 2 line hook + keywords natural + timestamps + links section, (3) 15 tags (mix: broad + specific + Hindi), (4) end screen plan, (5) pinned comment. YouTube India pe Hinglish search terms bhi include karo — jo log Hindi me search karte hain."},
{c:"Video", t:"Customer ki video testimonial lena", p:"Mere ek khush client se video testimonial record karwana hai call pe. Mujhe: (1) request message (aasan banao — 'phone se hi ho jayega'), (2) call pe 4 sawal jo unhone bolna hi aasan hai (pehle kaisa tha / ab kaisa hai / kya badla / kise recommend karega), (3) consent line recording shuru karne se pehle, (4) video ko 60-sec reel me convert karne ka plan (cut points, captions, end CTA). Client [client type] hai, service thi: [service]."},

// ============ DATA & EXCEL ============
{c:"Data", t:"Formula wala helper", p:"Mujhe Google Sheets/Excel me ye karna hai: [describe task — e.g. har client ka monthly total, overdue list, duplicate check]. Mujhe: (1) best formula/function ka naam + exact syntax mere case me (mera data columns me hai: [describe columns]), (2) formula step-by-step samjhao beginner ko, (3) 2 common galtiyan jo is formula me hoti hain, (4) agar formula na chale to alternate approach. Hindi explanation, formula English me."},
{c:"Data", t:"Sheet se dashboard banana", p:"Mera ye data hai: [describe — sales list, expenses, attendance etc., columns ka naam]. Mujhe ek dashboard design do us sheet ke dusre tab me: (1) kaunse 6 KPI cards (formulas ke saath), (2) kaunse 2 chart (chart type + kyun), (3) ek filter/dropdown jo main data me laga saku, (4) colors — simple, professional (company dashboard jaisa). Mujhe building order me batao taaki main 1 ghante me bana saku."},
{c:"Data", t:"Messy data clean karna", p:"Mere paas ye type ka kachha data hai: [describe mess — naam capitals mixed, dates alag format, phone numbers me +91 kuch me, duplicate rows]. Mujhe cleaning checklist do: har problem ka — (1) kaise pakdu (filter/sort trick), (2) kaise fix karu (formula ya manual), (3) kaise pata chalega clean ho gaya. Ye monthly karna hoga — isliye ek 'next time aisa hi ganda na ho' rule bhi 2 lines me."},
{c:"Data", t:"Weekly report automate", p:"Main har hafte ek [report type — sales/leads/attendance] report banata hoon jo 2 ghante lagte hain. Mujhe: (1) template design (columns/sections), (2) kaunse formulas/joins se numbers apne aap aayein, (3) ek 10-minute process jo har hafte follow karu (data daal → refresh → send), (4) ek WhatsApp-friendly 5-line summary format jo report ke upar jaye. Main [tool — Sheets/Excel] use karta hoon."},
{c:"Data", t:"Pivot table samajhna + banana", p:"Mujhe pivot table samajhna hai. Mera data: [describe — e.g. 500 rows, columns: date, client, service, amount]. Mujhe: (1) pivot kya karta hai — 2 line analogy (chacha ji ki diary type samjha ke), (2) mere data ka pehla pivot banane ke steps (rows, columns, values kya rakhu), (3) 3 sawal jo main pivot se turant answer kar paunga, (4) ek galti jo beginners pivot me karte hain. Step-by-step, [tool] ke interface ke hisaab se."},
{c:"Data", t:"Client tracker sheet — poora design", p:"Mujhe apne freelance/agency clients track karne ke liye ek Google Sheet chahiye. Mujhe pura design do: (1) tabs kya kya ho (Clients / Projects / Payments / Pipeline), (2) har tab ke exact column headers (naam, type, status, next action...), (3) dropdown values (status ke options), (4) 5 formulas jo must hain (overdue flag, total due, monthly income), (5) ek 'Sunday 10-min' update ritual. Main aaj hi bana saku itna clear ho."},
{c:"Data", t:"Charts jo samjhaayein, na ki dikhawein", p:"Mere paas ye data hai: [describe data]. Mujhe 3 chart options do — har ek ka: (1) chart type + kyun yahi (bar vs line vs pie ka logic), (2) kya dikhega x/y me, (3) ek line story jo wo bataega. Rule: chart ek hi message de — 3rd option me ek 'galti chart' bhi dikhao jo log banate hain aur usse kya problem hoti hai."},
{c:"Data", t:"Data entry kam karna", p:"Main [kaam] ke liye baar baar same data type karta hoon [kahan — sheet/app/form]. Mujhe: (1) 5 jagah jahan automation lag sakti hai (Google Forms → Sheet, scanner, voice typing, dropdown, template copy), (2) har ek ka setup — free tools se, steps, (3) kitna time bachega per week — realistic estimate, (4) kaunsa sabse pehle karu (effort vs saving). Main beginner hoon — jargon avoid karo."},

// ============ ECOMMERCE ============
{c:"Ecom", t:"Product listing copy jo beche", p:"Mera product: [product — details, price, audience]. Platform: [Amazon/Flipkart/Shopify/WhatsApp]. Mujhe: (1) title — keywords + benefit dono, (2) 5 bullet points (feature nahi — benefit likho, har bullet 'tuje kya milega' angle se), (3) description 100 words, (4) 5 search keywords jo log [platform] pe actually dhoondhte hain. Honest rakhna — jhootha claim nahi, jo product me hai wahi likhna."},
{c:"Ecom", t:"Store ka audit — 15 point", p:"Mujhe apna [Shopify/WhatsApp/Instamojo] store audit karne ka 15-point checklist do. Categories me: (1) trust (photos real? return policy? reviews?), (2) clarity (2 sec me samajh aata hai kya bech rahe? price clear?), (3) checkout (kitne steps? guest checkout? COD?), (4) mobile (text size? buttons thumb ke paas?), har point ke saath 'fail kaisa dikhega' bhi. Main khud audit kar lunga — framework do."},
{c:"Ecom", t:"Abandoned cart wapas laana", p:"Mere [platform] store pe log cart bhar ke chhod jaate hain. Mujhe 3 wapas laane wale touches: (1) WhatsApp message (3 line — reminder nahi, help angle: 'koi doubt?'), (2) 24 ghante baad — urgency honest wali (stock sach me hai to), (3) 3 din baad — last naya offer ya social proof. Templates + timing + ek rule: kitne baad me band (2 touches ke baad spam hai). India-specific: COD wale customers ka alag angle."},
{c:"Ecom", t:"COD follow-up system", p:"Mujhe COD orders confirm karne ka system chahiye — India me COD wale 30% cancel ho jaate hain. Mujhe: (1) order ke turant baad WhatsApp confirmation template (product + price + delivery expectation), (2) 1 din pehle delivery reminder, (3) 2 failed call ke baad message, (4) cancel hone par ek 'next time prepaid pe X% off' recovery message. Sab templates ready bhejo, Hinglish. Ek note bhi: COD cancel hone ka main reason kya hota hai India me — practical baat."},
{c:"Ecom", t:"Review machine", p:"Mujhe product reviews badhane ka honest system chahiye. Mujhe: (1) delivery ke [X] din baad review request message (product ka use aaya? 2-line feedback + photo), (2) khush customers se video review kaise maangu, (3) 5-star review public me kaise feature karu (story + product page), (4) 3-star review ka reply template. Fake review kabhi nahi — iska internal note bhi likho mere liye: fake review se kya hota hai (trust destroy + platform ban)."},
{c:"Ecom", t:"Margin wali pricing", p:"Mera product: [product], cost mujhe: ₹[cost], shipping ₹[ship], platform commission ~[%]. Mujhe: (1) bechni wali price 3 tiers (aggressive/balanced/premium) — har tier me margin kitna bachega, (2) India-specific: MRP vs selling price ka psychological game, (3) kab discount dena profitable hai (kitna % tak), (4) competitor [competitor price] pe bech raha hai — usko undercut karu ya nahi, logic do. Numbers ke saath calculation dikha."},
{c:"Ecom", t:"Festival sale ka plan", p:"[Festival — Diwali/Rakhi/EOSS] aa raha hai. Mera store: [niche, products]. Mujhe 2-hafte ka plan: (1) pre-sale (teaser, wishlist banao), (2) sale week (kaunse din kya offer — honest, maine decide karne ke liye options), (3) post-sale (review maangna, repeat ke liye email/WhatsApp), (4) ek rule: sale me wo discount jo main [X]% se zyada deep na ho. Content ideas bhi — 3 reel/story per phase."},

// ============ WRITING & ENGLISH ============
{c:"Writing", t:"Professional English email polish", p:"Ye mera draft email hai (main Hinglish me likhta hoon): [paste draft]. Mujhe iska professional English version do — par (1) simple English, corporate jargon nahi ('kindly do the needful' nahi), (2) short — kam se kam words, (3) polite par confident, (4) subject line 3 options. Saath me 1 line: kya badla aur kyun — taaki main seekh saku."},
{c:"Writing", t:"Grammar confident banane wala", p:"Mujhe apna English improve karna hai business ke liye — classes nahi, practice se. Mujhe: (1) mere 5 common galtiyan jo Indians karte hain (articles, tenses...) — har ek ka fix rule ek line me, (2) roz ka 10-min practice plan (kya karu: message Likhne ka, AI se check karwane ka), (3) ek habit: important message bhejne se pehle ka 3-second check ritual. Rules simple Hinglish me, examples English me."},
{c:"Writing", t:"Tone badalna — ek hi content", p:"Ye mera text hai: [paste]. Mujhe 4 versions do: (1) professional English (client email), (2) casual Hinglish (WhatsApp), (3) energetic (Instagram caption), (4) respectful senior wala (client jo bada aadmi hai). Content same, tone alag. Har version ke saath 1 line: kab use karna."},
{c:"Writing", t:"Proofread jaise editor kare", p:"Proofread ye text: [paste]. Mujhe: (1) grammar/spelling galtiyan — table me: galti → fix, (2) awkward lines → smooth versions, (3) jo cheez missing hai (context, number, next step — jo reader sochega 'aur?'), (4) final clean version. Tum ne improve kiya to bold nahi — simple list do taaki main samjh saku kya badla."},
{c:"Writing", t:"Hinglish se English document", p:"Ye meri [cheez — proposal/report/notes] Hinglish me hai: [paste]. Mujhe iska clean English document banao — structure: (1) headings, (2) short paragraphs, (3) bullets jahan list ho, (4) professional terms (par jargon nahi). Format aisa ho ki main seedha client ko bhej saku. Ek note end me: kaunse 3 words/phrases maine badle jo main agle baar khud use karu."},
{c:"Writing", t:"Job/application wala message", p:"Main [job/gig/internship] ke liye apply kar raha hoon. Mujhe: (1) application message/email — 100 words max, structure: kaun hu (1 line) → kya kar sakta (skills + 1 proof) → kyun ye role (1 line) → next step ask, (2) follow-up 5 din baad — 2 line, (3) ye 3 galtiyan jo applicants karte hain — mat karna inko. Mera background: [background]. English, simple, honest."},

// ============ TEAM & HIRING ============
{c:"Team", t:"VA ki job post", p:"Mujhe ek virtual assistant chahiye jo [tasks — data entry, follow-ups, content upload] kare. Mujhe job post likho: (1) title clear (role + kaam), (2) 5 bullet — kya karna hoga exactly, (3) 3 must-have skills (aur 3 'nice to have' alag se — filter ke liye), (4) hours/week + payment range ₹[X] honest, (5) application me 1 test question (jo sirf serious log karenge). Hinglish post, WhatsApp/Instagram story + Facebook group ke liye."},
{c:"Team", t:"VA ko kaam samjhana — SOP style", p:"Mujhe apne VA ko ye kaam samjhana hai: [task]. Mujhe ek instruction document banao jo main bhej saku: (1) kaam ka goal (1 line — kaam kya achieve kare), (2) steps numbered, har step: kya karna + kaise pata chalega sahi hua, (3) common doubt ka answer pehle se, (4) kahan ruk jana hai (jab confusion ho — 'sochna mat, mujhe screenshot bhejo'), (5) ek checklist jise VA complete karke wapas bheje. Hinglish, simple — VA bhi beginner ho sakta hai."},
{c:"Team", t:"Freelancer ka test task design", p:"Main [role — designer/editorer/developer] hire karne wala hoon. Mujhe ek paid test task design karo: (1) kaam: chhota (2-4 ghante ka) par REAL (mera actual kaam ka sample — toy nahi), (2) clear brief — kya milega, kya chahiye, kab, (3) evaluation: 5 criteria jispe main judge karu (quality, communication, deadline, questions puchne ka sense, instructions follow), (4) payment ₹[X] sabko ya sirf selected ko — pros/cons batao. Task aisa jo 30 min me judge ho sake."},
{c:"Team", t:"Delegation ka decision", p:"Mere paas ye kaam hain: [list tasks + time each]. Mujhe help karo decide karna: (1) kaunsa kaam maine karna chahiye (core/skill/revenue), (2) kaunsa delegate (repetitive, low-skill, time-heavy), (3) kaunsa DROP hi karna hai (ye sabse important column), (4) pehla delegation kaunsa — ek jo fail bhi ho jaye to sasta pade. 2x2 grid logic use karo: skill level x repeatability."},
{c:"Team", t:"Team member ki weekly check-in", p:"Mere team me [X] log hain (VA/freelancers). Mujhe weekly check-in system: (1) ek message template jo har member ko Monday jaye — 3 sawal: kya complete hua, kya atka hai, kya is week ka plan (sirf ye 3, essay nahi), (2) main unke jawab ka review ritual — 15 min me kaise: kya dekhna (red flags: 'atka tha aur nahi bataya'), (3) ek appreciation habit — har week 1 member ko 1 line praise (specific kaam ki, generic 'good job' nahi). Hinglish templates."},
{c:"Team", t:"Internship offer — chhota sa", p:"Mujhe ek intern chahiye [kaam] ke liye, unpaid nahi — chhota stipend ₹[X]. Mujhe: (1) offer message: kya milega intern ko (skills + certificate + real project name + reference), (2) 1-month structure: week-wise kya seekhayega aur kya kaam lega, (3) end me evaluation criteria — hire/no-hire ka honest rule, (4) ek rule: intern se kaam lena = sikhaana bhi. Ye dono side ke liye faayda wala hona chahiye — na ki sirf mera kaam nikalwana."},

// ============ MONEY BASICS ============
{c:"Money", t:"Freelance income ka system", p:"Mera income irregular hai — kuch mahine ₹[X], kuch ₹[Y]. Mujhe ek simple system: (1) 3-account rule (spending, tax-save, growth) — kitna % kahan, (2) 'lean month' fund — 2 mahine ka kharcha alag, (3) income tracking: ek sheet me kya-kya likhu (5 columns max), (4) mahine ka ek review sawal: 'kya main agle mahine 20% zyada kama sakta hoon — kaise?'. Simple banao — main finance padhna nahi chahta, system chahiye."},
{c:"Money", t:"Tax ka basic khauf khatam", p:"Main freelancer hoon, income ~₹[X]/month. Mujhe basic samjhao bina CA bane: (1) income tax: kis slab me aaunga roughly, ITR kaunsa type (kab file karu — date yaad dilana), (2) GST: mujhe registration chahiye ya nahi (threshold + services ka rule), (3) expenses jo main claim kar sakta hoon (internet, phone, laptop...) — proof kya rakhna, (4) 5 sawal jo main CA se puchu pehli baar milne pe. Ye general education hai — final numbers CA se confirm karunga, wo bhi likh ke de ki 'ye verify karna'."},
{c:"Money", t:"Paise ki aadat — 3 rule", p:"Mujhe paise bachane/augment karne ki aadat nahi hai — income aati hai, nikal jaati hai. Mujhe: (1) 'pay yourself first' ka automation — income aate hi kitna % kahan (simple, willpower par depend nahi), (2) 30-day tracking challenge — bas record karna, badalna nahi (kyunki pehle pata hona chahiye kahan ja raha), (3) ek 'bada kharcha' rule: ₹[X] se upar kuch bhi lene se pehle 48 ghante ka wait — isse impulse katta hai. 3 rules, bina lecture, bina jargon (FD, SIP baad me)."},
{c:"Money", t:"Rate badhne ka announcement", p:"Mere rate [purana rate] se [naya rate] ho rahe hain agle month se. Mujhe: (1) announcement message existing clients ke liye — thank + new rate + unke liye grandfather option (agar main du — decide karne ke liye pros/cons bhi), (2) naye leads ke liye updated pitch, (3) ek internal note: rate badhne ka best time kab (formula: calendar full + demand zyada), (4) 3 self-talk lines jab mujhe guilt ho rate bolne me. Hinglish, confident, apologetic nahi."},
{c:"Money", t:"Emergency fund — freelancer wala", p:"Freelancer hoon, income tikau nahi. Mujhe emergency fund ka realistic plan: (1) kitna chahiye (mera monthly kharcha ~₹[X] — 3/6 mahine ka rule + kyun utna), (2) kahan rakhun (3 options: savings, FD, liquid fund — risk vs access ka simple comparison, recommendation bhi), (3) kaise banau: monthly ₹[X] auto-transfer, (4) 'kya emergency hai aur kya nahi' ki honest list — phone toota emergency hai, sale emergency nahi. 100 words me ek line: aaj kya karna hai, bas wahi."},
{c:"Money", t:"Income streams ka tree", p:"Mere paas ye skill hai: [skill]. Abhi income sirf [current source] se hai. Mujhe income tree banao: (1) root — meri core skill, (2) 4 branches jo us skill se nikal sakte hain (service, digital product, teaching/content, tool/productized offer), (3) har branch: income potential range, time to first ₹, risk, (4) kaunsa branch pehle — logic (sabse fast cash + sabse low effort). Honest expectation do — '₹1L/mo passive in 30 days' wala jhooth nahi bolna."},

// ============ LEARNING ============
{c:"Learning", t:"Koi bhi skill 30 din me", p:"Main [skill] seekhna chahta hoon, level 0 se. Mujhe 30-day plan do: (1) pehle 5 din: basics itne ki main chhota kaam kar saku (kya-kya samjhna — topics ki list), (2) din 6-25: 3 projects (chhota → medium → portfolio-level), har project me kya banau + kaise pata chalega seekh gaya, (3) din 26-30: ek real-world piece (client-style kaam), (4) roz ka time [X min] realistic rakho, (5) ek rule: tutorial dekhna ≠ seekhna — 70% time BANANA, 30% dekhna. Resources ke naam mat bolna — topics batao, main khud dhoondhunga (tum outdated suggest kar sakte ho)."},
{c:"Learning", t:"Documentation/book kaise padhe", p:"Jab bhi main koi documentation, guide ya book padhta hoon to sab bhool jaata hoon. Mujhe: (1) padhne ka method — pehle skim (kya hai overall), phir targeted read (jo mujhe chahiye), phir DO (jo padha wo karke dekh), (2) notes ka format — 3 column: concept, mera example, kab use hoga (only this, essays nahi), (3) 'forget curve' ka hack: 24 ghante baad 5 min recall (book band karke likho kya yaad), (4) rule: ek chapter/section ka padhna + karna, 5 chapters ka sirf padhna se better. Method batao, motivation nahi."},
{c:"Learning", t:"Course kharidne se pehle", p:"Main [topic] ka course kharidne ka soch raha hoon — ₹[price]. Mujhe decision framework: (1) 5 sawal khud se — 'kya main is skill ka 1 free project kar chuka hoon?', 'kya course me main 90% content pehle se dekh chuka?', 'kya course ka outcome mere agle 6 mahine ke goal se juda hai?', (2) green-light rule: kitne haan hone pe kharidna theek, (3) red flags course me (jaldi-2 discount timer, 'passive income' promises, 0 refunds, reviews me sirf 'great course'), (4) option: course ke ₹X se main 1 mahine [alternative learning] — kab ye better hai. Honest framework — main course industry ka bhi victim hua hoon."},
{c:"Learning", t:"Seekha hua yaad rakhne ka system", p:"Main bahut kuch seekhta hoon par 2 hafte mein sab bhool jaata hoon. Mujhe ek personal knowledge system: (1) ek hi jagah capture karo — kaunsi (app/notebook), format: 3 sawal — kya seekha, example, kahan use hoga, (2) weekly 10-min: purani notes ka 1 randomly dhoondo → kya ab bhi apply kar sakta hoon?, (3) 'learn → use within 7 days' rule: jo seekha uska 1 real use within week, warna wo file me 'someday' chale jata hai, (4) mahine ka ek 'use it or lose it' din — purani seekh ko real kaam me lagana. Simple system, Notion-level complexity nahi."},
{c:"Learning", t:"Interview/exam prep fast", p:"Mujhe [interview/exam] ke liye [X din] hain. Syllabus/topics: [list]. Mujhe: (1) prioritized plan — 3 tiers: must-know (60% time), should-know (30%), skip if time (10%) — kaise decide karu ye logic bhi do, (2) active recall method — notes dobara padhna nahi, khud se test, (3) practice schedule — roz [X] questions/practice, (4) last 2 din ka special protocol (light revision + sleep pe focus, naya topic zero). Realistic banao — 12 ghante/din wala fantasy plan nahi."},

// ============ TOOLS & AUTOMATION ============
{c:"Tools", t:"Free tools ka stack audit", p:"Main ye kaam karta hoon: [list — content, design, outreach, tracking]. Mujhe mere har kaam ke liye: (1) ab main kya use karta hoon vs (2) ek ₹0 alternative (agar paisa de raha hoon bina zarurat), (3) ek automation idea — kaunse 2 tools jodke kitna time bachega (Zapier free tier / Make / n8n — jo fit ho), (4) priority: kaunsa automation pehle (weekly time saved calculation). Table format. India me available/free-tier wale tools hi bolna."},
{c:"Tools", t:"AI tools comparison — mere case ka", p:"Main [kaam] ke liye AI tool dhoondh raha hoon. Options jo main dekh raha hoon: [tools]. Mujhe: (1) har tool ka fit mere use case ke liye — strong + weak, (2) pricing India me (monthly ₹ me convert) + free tier ka sach, (3) '2 hufte ka trial plan' — har tool ko [X] din, kis task pe test karu, kya measure karu (speed, quality, integration), (4) final decision ka rule. Marketing bakwas skip karo — mere case ke liye honest assessment."},
{c:"Tools", t:"Automation ideas — meri rotein ki list", p:"Mere roz ke kaam: [list — jaise leads ko WhatsApp pe jawab, data entry, posting, follow-ups]. Mujhe 10 automation ideas nikalo — har ek: (1) kaunsa trigger (jab X ho), (2) kya ho automatic (Y ho jaye), (3) kis free/cheap tool se (Zapier/Make/WhatsApp Business/Sheet formulas), (4) setup time + weekly time saved. Rank: pehle wo jo setup 1 ghante me ho jaye aur roz 30 min bachaye. Aisa jo main akele kar saku, developer nahi chahiye."},
{c:"Tools", t:"WhatsApp Business setup — pro level", p:"Mujhe WhatsApp Business professional tarike se setup karna hai client work ke liye. Mujhe: (1) profile checklist (naam, category, description, catalog, timings, location), (2) greeting message template (jo pehli baar DM karne wale ko jaye — Hinglish, CTA ke saath), (3) away message + quick replies ke 5 must (rates, portfolio link, process, timeline, payment), (4) labels system — kaunse labels banau (New Lead, Hot, Client, Done) aur roz 5 min ka unhe aage badhne ka ritual, (5) catalog me kya daalu. Step-by-step — main aaj hi karlunga."},
{c:"Tools", t:"Backup — data khone se darr", p:"Mera kaam [describe — client files, designs, code, sheets] laptop me hai aur darr lagta hai kuch kho jaye. Mujhe ₹0 backup strategy: (1) 3-2-1 rule simple words me (3 copies, 2 jagah, 1 cloud), (2) kaunse free cloud tools (Google Drive 15GB, GitHub code ke liye, etc.) + kya kahan rakhu, (3) ek weekly ritual — Sunday 10 min: kya naya backup lena hai checklist, (4) 'kya ho gaya to main kya karunga' mini recovery plan — phone se kaam kaise chalu rahe. Aaj hi 30 min me ho jaye — itna simple banao."},
{c:"Tools", t:"Mere paas jo hai usse setup banana", p:"Mere paas ye hai: [jo bhi hai — phone, laptop, internet, skills]. Mujhe apna 'office' setup banao ₹0 me: (1) communication stack — kaunsa number/app client work ke liye (personal alag karna zaroori hai kya — haan, kyun), (2) files — folder structure ek baar banao (client/kaam/date), (3) payments — UPI + invoice ka minimal setup, (4) time tracking — simple (kabhi-kabhi kaam ka pata hi nahi chalta kitna laga), (5) ek 'day start' checklist — 5 min, roz. Aaj hi sab ho jaye — 2 ghante ka kaam max."}
];
